db:
  username: postgres
  password: root
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  properties:
    first: 1
    last: 2
    key: value
  pool:
    size: 10
    timeout: 20
  pools:
    - size: 10
      timeout: 20
    - size: 10
      timeout: 20
    - size: 10
      timeout: 20

logging:
  level:
    root: INFO
    by.javagur.spring.database.repository.pool: INFO
  file:
    name: by.javaguru
    path: /

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5432/springdata
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
  messages:
    basename: messages

app:
  image:
    bucket: E:\AAA\JavaGuru\JavaEnterprise\Projects\spring-starter-javaguru\images

app.service.logging:
  enabled: true